#!/bin/bash
set -eu
DIR="$(dirname "$0")"
cd "$DIR"

HBLOG="$DIR/../beepb00p"
SRC="$HBLOG/_site/"

SELF='sync' # script name


BEEPB00P_STABLE=yes "$HBLOG/rebuild"
rsync -av --delete --exclude "$SELF" --exclude ".git" "$SRC" .

git add --all
git commit -v -a
