#!/bin/bash
set -eu
DIR="$(dirname "$0")"
cd "$DIR"

HBLOG="$DIR/../beepb00p"
SRC="$HBLOG/_site/"

SELF='sync' # script name


BEEPB00P_STABLE=yes "$HBLOG/rebuild"
rsync -av --delete --exclude "$SELF" --exclude ".git" "$SRC" .

# meh
git add --all -- \
 :!heartbeats_vs_kcals_files/heartbeats_vs_kcals_11_0.png

git commit -v 
