#!/bin/bash
set -eux
DIR="$(dirname "$0")"
cd "$DIR"

HBLOG="$DIR/../beepb00p"
SRC="$HBLOG/_site/"

SELF='sync' # script name


BEEPB00P_STABLE=yes "$HBLOG/rebuild"

##
# some feed readers might not accept large RSS/atom feeds...
# TODO that's also argument against inline images I suppose
(( $(stat --printf="%s" $SRC/rss.xml ) < 512 * 1024 ))
(( $(stat --printf="%s" $SRC/atom.xml) < 512 * 1024 ))
##

##
# check for file:/// urls. linkchecker can't detect them, apparently :(
grep -r 'href="file://' "$SRC/" && exit 123
##

rsync -av --delete --exclude "$SELF" --exclude ".git" "$SRC" .

git add --all 

# meh
# -- \
# :!heartbeats_vs_kcals_files/heartbeats_vs_kcals_11_0.png

git commit -v 
